// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Api.Data;

#nullable disable

namespace OnlineStore.Api.Migrations
{
    [DbContext(typeof(OnlineStoreDbContext))]
    [Migration("20231205021144_ProductsMigration3")]
    partial class ProductsMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("OnlineStore.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineStore.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "194 Colors Cosmetic Make up Palette Set Kit with Eyeshadow Blusher Eyebrow Powder Face Concealer,All-in-One High Pigment Powder Pallet Kit with Mirror, Applicators",
                            ImageURL = "/Images/Beauty/Beauty1.png",
                            Name = "Cosmetic Make up palette",
                            Price = 23.99m,
                            Quantity = 125
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Bronzing powder that gives your skin a natural sunkissed look",
                            ImageURL = "/Images/Beauty/Beauty2.png",
                            Name = "Rimmel London Natural Bronzer",
                            Price = 5.97m,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "BEAKEY Diversity Makeup Brushes 12 Pcs Makeup Kit, Premium Synthetic Kabuki Foundation Face Powder Concealers Eyeshadow Blush Brushes Makeup Brush Set, with 2pcs Blender Sponges (Black/Silver)",
                            ImageURL = "/Images/Beauty/Beauty3.png",
                            Name = "BEAKEY Diversity Makeup Brushes 12 Pcs Makeup Kit",
                            Price = 6.78m,
                            Quantity = 175
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Very black volume mascara with curved silicone brush that has 6 different size bristles for an enhanced look Fan effect, No clumping, No smudging for extra-black volume even on the thinnest lashes. Place the brush at the base of your lashes and slightly twist upward to coat them;",
                            ImageURL = "/Images/Beauty/Beauty4.png",
                            Name = "Maybelline New York, Volume Mascara, Lash Sensational, Colour: Very Black, 9.5 mL",
                            Price = 7.07m,
                            Quantity = 280
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "AOOWU Glitter Powder Spray, Shiny Body Glitter Spray for Women, Highlighter Loose Powder Spray, Shimmer Sparkle Pearl Powder Makeup Spray for Body, Hair, Face and Clothing, Colorful White",
                            ImageURL = "/Images/Beauty/Beauty5.png",
                            Name = "Glitter Powder Spray",
                            Price = 6.29m,
                            Quantity = 147
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "A sturdy single plant pot perfect for your latest gardening venture",
                            ImageURL = "/Images/Garden/Garden1.png",
                            Name = "Single Plant Pot",
                            Price = 12.0m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "The perfect birthday present for anyone who loves gardening.",
                            ImageURL = "/Images/Garden/Garden2.png",
                            Name = "Multiple tool gardening set",
                            Price = 35.54m,
                            Quantity = 95
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "A single garden trowel",
                            ImageURL = "/Images/Garden/Garden3.png",
                            Name = "Garden Trowel",
                            Price = 4.99m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "The perfect watering can comes in the colour of yellow.",
                            ImageURL = "/Images/Garden/Garden4.png",
                            Name = "Watering Can",
                            Price = 14.99m,
                            Quantity = 19
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Footwear for a rainy day and for puddle splashing.",
                            ImageURL = "/Images/Garden/Garden5.png",
                            Name = "Wellington Boots",
                            Price = 65.0m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Airpods the perfect in ear wireless headphones.",
                            ImageURL = "/Images/Electronics/Electronic1.png",
                            Name = "Apple Airpods (3rd Generation)",
                            Price = 159.0m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "SteelSeries multi system wireless headset.",
                            ImageURL = "/Images/Electronics/Electronic2.png",
                            Name = "SteelSeries Arctis Nova 7",
                            Price = 129.0m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Razer BlackShark V2 Pro wireless premium gaming headset.",
                            ImageURL = "/Images/Electronics/Electronic3.png",
                            Name = "Razer BlackShark V2 Pro",
                            Price = 147.44m,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Duracell batteries with reliability for everyday devices.",
                            ImageURL = "/Images/Electronics/Electronic4.png",
                            Name = "Duracell Plus AA Batteries (24 pack)",
                            Price = 20.0m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Fitbit by Google, 7 days battery life.",
                            ImageURL = "/Images/Electronics/Electronic5.png",
                            Name = "Fitbit",
                            Price = 139.0m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Kitten heels are here to stay so stay on trend with our Millionaire slingback courts. This versatile style can be dressed up or down, with the adjustable sling back straps making them comfortable enough to take you from the office to the dancefloor.",
                            ImageURL = "/Images/Shoes/Shoes1.png",
                            Name = "Millionaire Point Court Kitten Heels",
                            Price = 39.99m,
                            Quantity = 36
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "The classic Boston clog by BIRKENSTOCK, designed to wear all year round. The adaptable strap and strong metal buckle, along with foam layered soft footbed make these clogs comfortable for all foot types. With Suede lining and upper and Birko-Flor®, a flawless imitation of real nubuck. This pair has a narrow fit.",
                            ImageURL = "/Images/Shoes/Shoes2.png",
                            Name = "BIRKENSTOCK Boston Clogs",
                            Price = 115.0m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Office Monroe derby shoes perfect for smart occasions.",
                            ImageURL = "/Images/Shoes/Shoes3.png",
                            Name = "Monroe Derby Shoes",
                            Price = 44.99m,
                            Quantity = 58
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Bronx Daff Buckle Knee High Boots made out of leather and with a rubber sole.",
                            ImageURL = "/Images/Shoes/Shoes4.png",
                            Name = "Bronx Daff Buckle Knee High Boots",
                            Price = 160.0m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Vagabond Shoemakers Kenova Stretch Boots, comfy pull on fit and with a synthetic sole.",
                            ImageURL = "/Images/Shoes/Shoes5.png",
                            Name = "Vagabond Shoemakers Kenova Stretch Boots",
                            Price = 165.0m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "The ground-breaking second novel from the internationally bestselling author of I AM PILGRIM",
                            ImageURL = "/Images/Books/Books-Yearoflocust.png",
                            Name = "The year of the locust",
                            Price = 16.99m,
                            Quantity = 33
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Traumatised by the death of a child in her care, top London paediatrician Claire seeks refuge on remote Selkie Island in the wilds of the Irish Sea with her husband Daniel and their baby daughter Kitty. Hidden away in Daniel’s old family home, Claire hopes to be as cut off from her guilt as she is from the mainland, but can she find peace in a place so full of its own secrets?",
                            ImageURL = "/Images/Books/Books-TheIslanders.png",
                            Name = "The Islanders",
                            Price = 6.99m,
                            Quantity = 64
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "I take a deep breath as I pull up to the glass-fronted lodge my ex-mother-in-law, Angela, has booked for her birthday. I didn’t want to come on holiday with my ex-husband and his new wife, but she insisted that me and my children play happy families. It isn’t exactly my idea of fun, but Angela has always been kind to me, and the kids are happy. I try to ignore the snow clouds gathering above. The last thing I want is to be trapped here.",
                            ImageURL = "/Images/Books/Books-TheLodge.png",
                            Name = "The Lodge",
                            Price = 8.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "From the bestselling author of What You Did comes the story of a young couple who are about to discover that in a house full of secrets there’s nowhere to hide…",
                            ImageURL = "/Images/Books/Books-LetMeIn.png",
                            Name = "LET ME IN",
                            Price = 6.99m,
                            Quantity = 74
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Religion is a competitive business in the Discworld. Everyone has their own opinion and their own gods, of every shape and size - all fighting for faith, followers, and a place at the top.",
                            ImageURL = "/Images/Books/Books-SmallGods.png",
                            Name = "Small Gods",
                            Price = 9.19m,
                            Quantity = 174
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "We live in an interesting time. Materially, everything is the best it’s ever been—we are freer, healthier and wealthier than any people in human history. Yet, somehow everything seems to be irreparably and horribly f*cked—the planet is warming, governments are failing, economies are collapsing, and everyone is perpetually offended on Twitter. At this moment in history, when we have access to technology, education and communication our ancestors couldn’t even dream of, so many of us come back to an overriding feeling of hopelessness.",
                            ImageURL = "/Images/Books/Books-Everythingisfucked.png",
                            Name = "Everything is F*cked",
                            Price = 11.95m,
                            Quantity = 201
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "Same As Ever will arm you with a powerful new ability to think about risk and opportunity, and navigate the uncertainty of the future. When planning for the future, we often ask something like, “What will the economy be doing this time next year?” Or we want to know, “What will be different ten years from now?”",
                            ImageURL = "/Images/Books/Books-Sameasever.png",
                            Name = "Same as ever",
                            Price = 11.99m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "At the very heart of all the success and failure I've been exposed to - both my own entrepreneurial journey and through the thousands of interviews I've conducted on my podcast - are a set of principles that can stand the test of time, apply to any industry, and be used by anyone who is search of building something great or becoming someone great.",
                            ImageURL = "/Images/Books/Books-DiaryofCEO.png",
                            Name = "The Diary Of A CEO",
                            Price = 10.00m,
                            Quantity = 89
                        });
                });

            modelBuilder.Entity("OnlineStore.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fa-solid fa-paintbrush",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fa-solid fa-worm",
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fa-solid fa-headset",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fa-solid fa-socks",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 5,
                            IconCSS = "fa-solid fa-book",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("OnlineStore.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Harry"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });

            modelBuilder.Entity("OnlineStore.Api.Entities.Product", b =>
                {
                    b.HasOne("OnlineStore.Api.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
